### PR TITLE
Added Careers Modal

### PR DESCRIPTION
**Pull request by nckz**
This patch changes the 'Hiring' button title to 'Careers'; the button now opens a modal with sample dialogue and a button-link to the breezy job listings site.

image

image

### CODE REVIEW

**Comment by nckz** [comment]
This patch is waiting for the text that is supposed to go into the 'Careers' modal.

**Comment by bennashman** [comment]
> This patch is waiting for the text that is supposed to go into the 'Careers' modal.

I've got a draft of text that I'm going to confirm and will get back to you shortly

**Comment by nckz** [comment]
The modal now looks like this:

image

**Comment by bennashman** [comment]
@nckz Small bug I found. When I hover over all the buttons, they should change the mouse icon to the open hand. This happens for all of them except for the "Careers" button. I can report this as a bug if easier.

**Pull request merged**
